### ISSUE TITLE
Error: Checksum of downloaded artifact of binary target 'SeonSDK' does not match checksum specified by the manifest

### ISSUE THREAD

**Issue by RomanPronskiy** [seontechnologies/seon-ios-sdk-swift-package#10]
Hey @robertorsulics-seon, I can not download SDK using Xcode build command tool
while trying to link SDK to the project using:
`.package(url: "https://github.com/seontechnologies/seon-ios-sdk-swift-package", from: "5.4.2")`

Getting an error:
```
xcodebuild: 
error: Could not resolve package dependencies:
checksum of downloaded artifact of binary target 'SeonSDK' (554756711bf17df0ce5ab7d50ad0eaffe831c5accd8dbe01078b6e9ebe85c21f) 
does not match checksum specified by the manifest (56c10fb719370055a39d4efd207e0e4c18bd74e25c90a112f095278ecb2abd72)
fatalError
```

Could you please assist us with resolving this error?

p.s.
Have cleaned all caches of Xcode and SPM and it didn't help
for example here` ~/Library/Caches/org.swift.swiftpm`,
derived data, trash can and so on.

**Comment by anilsudhakaran-chipotle** [comment]
Same but for version 5.2

**Comment by anilsudhakaran** [comment]
Same for 5.2

**Comment by szabolcsadam-seon** [comment]
Please note that if you still encounter an error on 5.4.2, you should delete the Swift security fingerprint cache for this library. 
You should delete the `seon-ios-sdk-swift-package-{commit-hash}.json` file from `/Library/org.swift.swiftpm/security/fingerprints`

Or you can delete every fingerprint (not advised): 
`rm -rf ~/Library/org.swift.swiftpm/security/fingerprints`

**Comment by RomanPronskiy** [comment]
Thank you @szabolcsadam-seon, updating setting `version 5.4.2` and removing `org.swift.swiftpm` file resolved the issue, this time.
